export const TOKENS = {
  CUSTOMER_AUTH_PORT: 'CUSTOMER_AUTH_PORT',
  CATALOG_READ_PORT: 'CATALOG_READ_PORT',
  ORDER_READ_PORT: 'ORDER_READ_PORT',
  SEARCH_PORT: 'SEARCH_PORT',
  SESSION_REPOSITORY: 'SESSION_REPOSITORY',
  RATE_LIMIT_SERVICE: 'RATE_LIMIT_SERVICE',
} as const;
